### ISSUE TITLE
info in the instructions misleading around default hashtags

### ISSUE THREAD

**Issue by cori** [phonetonote/ptn-roam-depot#4]
Roam Depot config page states

> if you want #hashtag at the end of each phonetoroam note, put what you want that hashtag to be here. if you do not want a hashtag, make this blank.

but in reality leaving it blank means they get a #ptn hashtag. That's totally fine, but it seems like the instructions should call it out.

**Comment by scottrblock** [comment]
thanks @cori, i think ideally it should still support no hashtag, so i'd consider this a bug with the current roam depot implementation

**Comment by scottrblock** [comment]
Whoops, github somehow auto merged that based on my commit message, will close this when this actually ships

**Comment by scottrblock** [comment]
This fix is now live in roam depot, just update your extension to get it.
